version: '2'
services:
  api-template:
    build:
      context: .
    environment:
      DB_USER: autio
      DB_PASS: autio
      DB_NAME: autio
      DB_HOST: db
      DB_PORT: 5432
      PORT: 8082
    networks:
      - api-lan
      - internet

  api:
    extends:
      service: api-template
    command:  bash -c 'mkdir -p /app/node_modules/.yarn-cache; cd /app && yarn --cache-folder /app/node_modules/.yarn-cache && npm run db:migrate && npm run api'
    build:
      dockerfile: Dockerfile.development
    links:
      - postgres:db
    ports:
      - "8082:8082"
    volumes:
      - "./dist:/app/dist"
      - "./api:/app/api"
      - "./infrastructure:/app/infrastructure"
      - "./core:/app/core"
      - "./scripts:/app/scripts"
      - "./package.json:/app/package.json"
      - 'api-nodemodules-dev:/app/node_modules'
      - 'api-npmhome-dev:/home/app/.npm'
    
  postgres:
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: autio
      POSTGRES_PASSWORD: autio
      POSTGRES_DB: autio
    image: postgres:9.5.4
    networks:
      - api-lan

volumes:
  api-nodemodules-dev:
  api-npmhome-dev:
  api-npmhome-staging:


networks:
  internet:
  api-lan: